baseURL = 'https://gboere.github.io/'
locale = 'en-us'
title = 'Portfolio'


[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
